In [ ]:
import numpy as np
import random

def create_feature_matrix(rows, cols):
    # Creates a feature matrix with random values.
    feature_matrix = [[random.randint(0, 100) for _ in range(cols)] for _ in range(rows)]
    print("Feature Matrix:")
    for row in feature_matrix:
        print(row)
    return np.array(feature_matrix)

def create_filter_matrix(rows, cols):
    # Creates a filter matrix with random values.
    filter_matrix = [[random.randint(0, 100) for _ in range(cols)] for _ in range(rows)]
    print("Filter Matrix:")
    for row in filter_matrix:
        print(row)
    return np.array(filter_matrix)

def apply_filter_vectorized(feature_matrix, filter_matrix, padding=0, stride=1):
    # Pad the feature matrix
    if padding > 0:
        feature_matrix = np.pad(feature_matrix, ((padding, padding), (padding, padding)), mode='constant')

    # Calculate output dimensions
    output_height = (feature_matrix.shape[0] - filter_matrix.shape[0]) // stride + 1
    output_width = (feature_matrix.shape[1] - filter_matrix.shape[1]) // stride + 1

    # Initialize the output matrix
    output_matrix = np.zeros((output_height, output_width))

    # Apply the filter using a sliding window
    for i in range(output_height):
        for j in range(output_width):
            region = feature_matrix[i * stride:i * stride + filter_matrix.shape[0],
                                    j * stride:j * stride + filter_matrix.shape[1]]
            output_matrix[i, j] = np.sum(region * filter_matrix)

    return output_matrix

def main():
    try:
        feature_rows = int(input("Enter the number of rows for the input image: "))
        feature_cols = int(input("Enter the number of columns for the input image: "))
        filter_rows = int(input("Enter the filter size (height): "))
        filter_cols = int(input("Enter the filter size (width): "))

        if filter_rows > feature_rows or filter_cols > feature_cols:
            raise ValueError("Filter dimensions cannot be larger than the feature matrix dimensions.")

        feature_matrix = create_feature_matrix(feature_rows, feature_cols)
        filter_matrix = create_filter_matrix(filter_rows, filter_cols)

        padding = int(input("Enter the padding value: "))
        stride = int(input("Enter the stride value: "))

        output_matrix = apply_filter_vectorized(feature_matrix, filter_matrix, padding, stride)

        print("Output Matrix:")
        print(output_matrix)

    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()

Enter the number of rows for the input image: 10
Enter the number of columns for the input image: 10
Enter the filter size (height): 3
Enter the filter size (width): 3
Feature Matrix:
[90, 94, 12, 74, 1, 28, 99, 84, 45, 1]
[62, 48, 47, 8, 74, 34, 64, 38, 47, 75]
[47, 49, 14, 58, 74, 47, 56, 36, 80, 14]
[16, 38, 100, 15, 85, 13, 22, 18, 27, 53]
[6, 29, 9, 21, 40, 4, 38, 100, 41, 87]
[87, 52, 79, 32, 53, 75, 96, 8, 82, 1]
[85, 47, 43, 46, 31, 71, 83, 75, 4, 24]
[24, 94, 74, 94, 15, 96, 7, 95, 93, 66]
[59, 27, 3, 88, 54, 90, 100, 37, 78, 49]
[73, 16, 35, 18, 58, 58, 72, 58, 83, 11]
Filter Matrix:
[94, 36, 98]
[89, 50, 22]
[93, 81, 39]
Enter the padding value: 2
Enter the stride value: 2
Output Matrix:
[[ 3510. 16452.  7149.  6222. 17766.  4266.]
 [12017. 30858. 18987. 33371. 36614. 20773.]
 [ 5192. 16336. 26274. 28361. 31085. 23937.]
 [ 5817. 27960. 24253. 30078. 35888. 16650.]
 [11159. 30151. 29865. 36105. 33652. 24040.]
 [ 7388. 14879. 14033. 27762. 29510. 17033.]]


In [ ]:
import numpy as np

class ActivationFunctions:

    @staticmethod
    def sigmoid(x):
        return 1 / (1 + np.exp(-x))

    @staticmethod
    def sigmoid_derivative(x):
        sigmoid_x = ActivationFunctions.sigmoid(x)
        return sigmoid_x * (1 - sigmoid_x)

    @staticmethod
    def relu(x):
        return np.maximum(0, x)

    @staticmethod
    def relu_derivative(x):
        return (x > 0).astype(float)

    @staticmethod
    def tanh(x):
        return np.tanh(x)

    @staticmethod
    def tanh_derivative(x):
        return 1 - np.tanh(x)**2


# Example usage
if __name__ == "__main__":
    # Sample input
    x = np.array([-1, 0, 1, 2, 3])

    print("Sigmoid:")
    print("Forward:", ActivationFunctions.sigmoid(x))
    print("Derivative:", ActivationFunctions.sigmoid_derivative(x))

    print("\nReLU:")
    print("Forward:", ActivationFunctions.relu(x))
    print("Derivative:", ActivationFunctions.relu_derivative(x))

    print("\nTanh:")
    print("Forward:", ActivationFunctions.tanh(x))
    print("Derivative:", ActivationFunctions.tanh_derivative(x))
